spring:
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xyiot?useSSL=false&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: 123456
    autoCommit: false
    minIdle: 5
    maximumPoolSize: 20
    connectionInitSql: select 1
    hikari:
      idle-timeout: 10000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    #允许bean重复定义，后面的覆盖前面的
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: UTF-8

server:
  port: 8100
  compression:
    enabled: true
  servlet:
    context-path: /event

management:
  server:
    port: 9002
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  mapperLocations: classpath*:net/xuanyutech/**/dao/*.xml
  # 这个很重要
  basePackage: '**.dao'


#日志
logging:
  level:
    ROOT: info
    org.apache.kafka: ERROR
    org.springframework.kafka: ERROR

test:
  name: syj
  describe: this is a test.




